import { Car } from './types';

export const CARS: Car[] = [
  {
    id: 'kia-k5',
    name: 'Kia K5',
    brand: 'Kia',
    category: 'sedan',
    seats: 5,
    year: 2023,
    transmission: 'auto',
    fuel: 'gasoline',
    pricePerDay: 950000,
    pricePerMonth: 18000000,
    image: 'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800&q=80',
    features: '<ul><li>Màn hình cảm ứng 10"</li><li>Camera 360°</li><li>Cảnh báo làn đường</li><li>Điều hòa tự động</li></ul>',
    available: true,
  },
  {
    id: 'hyundai-tucson',
    name: 'Hyundai Tucson',
    brand: 'Hyundai',
    category: 'suv',
    seats: 5,
    year: 2023,
    transmission: 'auto',
    fuel: 'gasoline',
    pricePerDay: 1100000,
    pricePerMonth: 22000000,
    image: 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&q=80',
    features: '<ul><li>SUV cao cấp</li><li>Cốp điện</li><li>Phanh tự động</li><li>Ghế da cao cấp</li></ul>',
    available: true,
  },
  {
    id: 'toyota-innova',
    name: 'Toyota Innova Cross',
    brand: 'Toyota',
    category: 'mpv',
    seats: 7,
    year: 2024,
    transmission: 'auto',
    fuel: 'hybrid',
    pricePerDay: 1300000,
    pricePerMonth: 26000000,
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80',
    features: '<ul><li>Hybrid tiết kiệm</li><li>7 chỗ rộng rãi</li><li>Cửa lùa điện</li><li>Android Auto</li></ul>',
    available: true,
  },
  {
    id: 'mercedes-c200',
    name: 'Mercedes C200',
    brand: 'Mercedes-Benz',
    category: 'luxury',
    seats: 5,
    year: 2023,
    transmission: 'auto',
    fuel: 'gasoline',
    pricePerDay: 2800000,
    pricePerMonth: 55000000,
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
    features: '<ul><li>Sang trọng đẳng cấp</li><li>Massage ghế trước</li><li>Head-up display</li><li>Ambient lighting</li></ul>',
    available: true,
  },
  {
    id: 'ford-ranger',
    name: 'Ford Ranger Wildtrak',
    brand: 'Ford',
    category: 'suv',
    seats: 5,
    year: 2023,
    transmission: 'auto',
    fuel: 'diesel',
    pricePerDay: 1200000,
    pricePerMonth: 23000000,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    features: '<ul><li>4WD địa hình</li><li>Kéo tải 3.5 tấn</li><li>Bán tải mạnh mẽ</li><li>Thùng xe rộng</li></ul>',
    available: true,
  },
  {
    id: 'toyota-vios',
    name: 'Toyota Vios',
    brand: 'Toyota',
    category: 'sedan',
    seats: 5,
    year: 2023,
    transmission: 'auto',
    fuel: 'gasoline',
    pricePerDay: 700000,
    pricePerMonth: 14000000,
    image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
    features: '<ul><li>Tiết kiệm nhiên liệu</li><li>Dễ lái nội thành</li><li>Bảo hiểm đầy đủ</li><li>GPS tracking</li></ul>',
    available: true,
  },
];

export const PICKUP_LOCATIONS = [
  'Hoàn Kiếm, Hà Nội',
  'Cầu Giấy, Hà Nội',
  'Đống Đa, Hà Nội',
  'Hai Bà Trưng, Hà Nội',
  'Nam Từ Liêm, Hà Nội',
  'Sân bay Nội Bài',
  'Ga Hà Nội',
  'Địa điểm khác (ghi rõ trong ghi chú)',
];

export const COMPANY_INFO = {
  name: 'Hanoi Tourism',
  tagline: 'Dịch vụ cho thuê xe uy tín tại Hà Nội',
  phone: '0912 345 678',
  email: 'info@hanoitourism.vn',
  address: '123 Phố Huế, Hai Bà Trưng, Hà Nội',
  zaloNumber: '0912345678',
  workingHours: '7:00 - 22:00 (Tất cả các ngày)',
  foundedYear: 2015,
  totalCars: 200,
  totalClients: 15000,
  provinces: 63,
};

export const formatCurrency = (amount: number): string =>
  new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(amount);

export const formatDate = (dateStr: string): string =>
  new Date(dateStr).toLocaleDateString('vi-VN', {
    day: '2-digit', month: '2-digit', year: 'numeric',
  });
